services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  petclinic:
    image: springcommunity/spring-petclinic-microservices:latest
    container_name: petclinic
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    depends_on:
      - petclinic
    volumes:
      - ./locust:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --host http://petclinic:8080
